name: Build and Release Mod
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8
          cache-disabled: true # Temporarily disable cache to bypass the GitHub outage

      - name: Build with Gradle
        run: |
          gradle build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build # This forces it to create/update a release named "latest-build"
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
